spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_vue_sample
    username: takachanman
    password:
    driver-class-name: org.postgresql.Driver
  # jpa:
  #   show-sql: true
    
server:
  port: 8888